version: '3.8'

services:
  paperscan-app:
    build: .
    container_name: paperscan_contenedor
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./datos:/app/datos
      - ./local:/app/local
    environment:
      - ARXIV_CONTACTO_EMAIL=correo@dominio.com
    stdin_open: true
    tty: true